### ISSUE TITLE
能否提供在线预览地址及项目相关文档？

### ISSUE THREAD

**Issue by zhangpeng2k** [push-over/vue-h5-template#1]
能否提供在线预览地址及项目相关文档？

**Comment by push-over** [comment]
> 能否提供在线预览地址及项目相关文档？

好的 我会尽快更新一份使用文档

**Comment by push-over** [comment]
> 能否提供在线预览地址及项目相关文档？

已出使用说明

**Comment by tyler4400** [comment]
挺不错的。不过好像还在初期，能不能发展到[vue-element-admin](https://github.com/PanJiaChen/vue-element-admin)那样。

**Comment by next2014** [comment]
> 挺不错的。不过好像还在初期，能不能发展到[vue-element-admin](https://github.com/PanJiaChen/vue-element-admin)那样。

卖广告

**Comment by push-over** [comment]
> 挺不错的。不过好像还在初期，能不能发展到[vue-element-admin](https://github.com/PanJiaChen/vue-element-admin)那样。

花裤衩给了你多少广告费  哈哈
